course_code <- "CSCD84"
course_full_name <- "Artificial Intelligence"
university <- "University of Toronto Scarborough"
department <- "Computer & Mathematical Science"
season <- "Winter"
year <- "2024"
zoom_lec_l <- "https://utoronto.zoom.us/j/84800897084"
quercus_l <- "https://q.utoronto.ca/courses/332889"
crowdmark_l <- "https://crowdmark.com"